plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  cpu:
    - x64
  libc:
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
